export const actionIds = {
    UPDATE_MEMBERS: 'UPDATE_MEMBERS',
    FETCH_MEMBERS_ERROR: 'FETCH_MEMBERS_ERROR',
    UPDATE_PAGE: 'UPDATE_PAGE',
    CLEAR_TABLE: 'CLEAR_TABLE',
    FETCH_MEMBERS_DETAILS: 'FETCH_MEMBERS_DETAILS',
  };